"""create workload column in course table

Revision ID: 7d1aa4b1fb88
Revises: 9af823112039
Create Date: 2025-02-10 18:46:40.258429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1aa4b1fb88'
down_revision: Union[str, None] = '9af823112039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('class_hours', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'class_hours')
    # ### end Alembic commands ###
