"""create period column in course table

Revision ID: ac7d0daf5c24
Revises: 7d1aa4b1fb88
Create Date: 2025-02-10 20:55:49.883511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7d0daf5c24'
down_revision: Union[str, None] = '7d1aa4b1fb88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('period', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'period')
    # ### end Alembic commands ###
